development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: aggieexperts_dev
  pool: 5
  username: aggieexperts
  password: cloudstack#
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: aggieexperts_test
  pool: 5
  username: aggieexperts
  password: cloudstack#
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: aggieexperts_prod
  pool: 5
  username: aggieexperts
  password: cloudstack#