development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: aggieexperts_test
  pool: 5
  username: aggieexperts
  password: cloudstack#
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: aggieexperts_prod
  pool: 5
  username: aggieexperts
  password: cloudstack#
cucumber:
  <<: *test
